version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5435:5431
    environment:
      POSTGRES_PASSWORD: admin
  api:
    build: .
    ports:
      - 8080:8080
    restart: on-failure:10
    environment:
      - PORT=8080
      - DATABASE_URL=postgres:admin@localhost:5431/postgres?sslmode=disable
    depends_on:
      - db
      
