version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: admin
  api:
    build: .
    ports:
      - 8080:8080
    restart: on-failure:10
    environment:
      - PORT=8080
      - DATABASE_URL=db
    depends_on:
      - db
  migrate:
    image: migrate/migrate
    command: [ "-path", "/migrations", "-database",  "postgresql://postgres:admin@db:5432/postgres?sslmode=disable", "up" ]
    volumes:
      - ./migrations:/migrations
    restart: on-failure
    depends_on:
      - db
      
